= 미믹스튜디오 API Guide #1
박동주;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[server_info]]
== Server Info
현재 배포중인 서버 도메인 정보입니다.

|===
| Name | Domain | Docs | Descript

| Dev Server
| https://dev.leaguewin.ml
| https://dev.leaguewin.ml/docs
| 3D 아이템, 유저 관련 API

| Video Server
| https://dev.leaguewin.ml/video
| https://dev.leaguewin.ml/video/docs
| Video 업로드 및 사진 추출 서버

|===

[[overview_http_verbs]]
== HTTP verbs

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PATCH`
| Used to update an existing resource, including partial updates

| `DELETE`
| Used to delete an existing resource
|===

[[overview_http_status_codes]]
== HTTP status codes

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist
|===

[[resources_items]]
== /members

회원 관련 API 입니다.

[[resources_members_signup]]
=== 회원가입

`POST` 요청을 사용해 새로운 회원을 등록합니다.
`accessToken` 을 반환하고 `refreshToken` 을 쿠키로 등록합니다.

operation::members-signup[snippets='request-fields,http-request,response-headers,response-fields,http-response']

[[resources_members_login]]
=== 로그인

`POST` 요청으로 회원 가입된 계정에 로그인합니다.
`accessToken` 을 반환하고 `refreshToken` 을 쿠키로 등록합니다.

operation::members-login[snippets='request-fields,http-request,response-headers,response-fields,http-response']

[[resources_members_modify]]
=== 정보 수정
`PUT` 요청으로 회원 정보를 수정합니다.

operation::members-modify[snippets='request-fields,http-request,http-response']

[[resources_members_check_email]]
=== Email 검증
이메일이 중복되었는지 체크합니다.

operation::members-check-email[snippets='request-fields,http-request,response-fields,http-response']


[[resources_members_check_account]]
=== Account 검증
계정 이름(Account)이 중복되었는지 체크합니다.

operation::members-check-account[snippets='request-fields,http-request,response-fields,http-response']


[[resources_members_refresh]]
=== 액세스 토큰 재발급
액세스 토큰이 만료된 경우 리프레쉬 토큰을 사용해 재발급 받을 수 있습니다.
리프레쉬 토큰이 쿠키로 등록되어 있어야 합니다.
리프레쉬 토큰까지 만료된 경우 다시 로그인 해야 합니다.

operation::members-refresh[snippets='http-request,response-fields,http-response']

[[resources_members_myinfo]]
=== 내 정보 확인

`GET` 요청으로 로그인된 내 정보를 확인합니다.
`Authorization` 헤더를 `Bearer access_token` 으로 설정해야합니다.

operation::members-myinfo[snippets='request-headers,http-request,response-fields,http-response']



[[resources_items]]
== /3d-items

3D 아이템 관련 API 입니다.

[[resources_items_create]]
=== 3D 아이템 생성

`POST` 요청을 사용해 새로운 3D 아이템을 등록하고 모델링을 시작합니다.

operation::item-create[snippets='request-fields,http-request,response-fields,http-response']

=== 3D 아이템 조회 (One)

`GET` 요청으로 item_id를 받아 특정 3D 아이템 정보를 조회합니다.

operation::item-findOne[snippets='http-request,response-fields,http-response']

[[resources_items_list]]
=== 3D 아이템 조회 (Search and Pagination)

`GET` 요청으로 특정 조건의 3D 아이템 정보를 조회합니다.

operation::item-pagination1[snippets='request-fields']
operation::item-findAll[snippets='http-request,response-fields,http-response']

==== 페이지네이션 1
operation::item-pagination1[snippets='http-request,http-response']
==== 페이지네이션 2
operation::item-pagination2[snippets='http-request,http-response']

[[resources_items_remove]]
=== 3D 아이템 삭제

`DELETE` 요청으로 item_id를 받아 특정 3D 아이템을 삭제합니다.

operation::item-remove[snippets='http-request,http-response']

[[resources_items_apply_coin]]
=== 아이템 코인 신청

아이템을 생성하기 위한 코인을 신청합니다.

operation::item-coin-apply[snippets='request-fields,http-request,http-response']

